export type Province = {
  name: string;
  abbreviation: string;
};

export const provinces = [
  {
    name: 'Alberta',
    abbreviation: 'AB',
  },
  {
    name: 'British Columbia',
    abbreviation: 'BC',
  },
  {
    name: 'Manitoba',
    abbreviation: 'MB',
  },
  {
    name: 'New Brunswick',
    abbreviation: 'NB',
  },
  {
    name: 'Newfoundland and Labrador',
    abbreviation: 'NL',
  },
  {
    name: 'Nova Scotia',
    abbreviation: 'NS',
  },
  {
    name: 'Ontario',
    abbreviation: 'ON',
  },
  {
    name: 'Prince Edward Island',
    abbreviation: 'PE',
  },
  {
    name: 'Quebec',
    abbreviation: 'QC',
  },
  {
    name: 'Saskatchewan',
    abbreviation: 'SK',
  },
  {
    name: 'Northwest Territories',
    abbreviation: 'NT',
  },
  {
    name: 'Nunavut',
    abbreviation: 'NU',
  },
  {
    name: 'Yukon',
    abbreviation: 'YT',
  },
] as Province[];

export const cities = {
  ON: [
    'Toronto',
    'Ottawa',
    'Mississauga',
    'Brampton',
    'Hamilton',
    'London',
    'Markham',
    'Vaughan',
    'Kitchener',
    'Windsor',
    'Richmond Hill',
    'Sudbury',
    'Oshawa',
    'Barrie',
    'Guelph',
    'Kingston',
    'Cambridge',
    'St. Catharines',
    'Thunder Bay',
    'Waterloo',
  ],
  BC: [
    'Vancouver',
    'Victoria',
    'Surrey',
    'Burnaby',
    'Richmond',
    'Kelowna',
    'Abbotsford',
    'Coquitlam',
    'Langley',
    'Nanaimo',
    'Kamloops',
    'Chilliwack',
    'Maple Ridge',
    'Prince George',
    'New Westminster',
    'Penticton',
    'North Vancouver',
    'Port Coquitlam',
    'Vernon',
    'Campbell River',
  ],
  AB: [
    'Calgary',
    'Edmonton',
    'Red Deer',
    'Lethbridge',
    'St. Albert',
    'Medicine Hat',
    'Grande Prairie',
    'Airdrie',
    'Spruce Grove',
    'Leduc',
    'Fort McMurray',
    'Lloydminster',
    'Brooks',
    'Okotoks',
    'Chestermere',
  ],
  MB: [
    'Winnipeg',
    'Brandon',
    'Steinbach',
    'Portage la Prairie',
    'Thompson',
    'Selkirk',
    'Winkler',
    'Dauphin',
    'Morden',
    'Flin Flon',
    'The Pas',
    'Stonewall',
    'Neepawa',
    'Niverville',
    'Swan River',
  ],
  NB: [
    'Moncton',
    'Saint John',
    'Fredericton',
    'Dieppe',
    'Miramichi',
    'Edmundston',
    'Bathurst',
    'Campbellton',
    'Shediac',
    'Oromocto',
    'Grand Bay-Westfield',
    'Quispamsis',
    'Riverview',
    'Rothesay',
    'Tracadie',
  ],
  NL: [
    "St. John's",
    'Mount Pearl',
    'Corner Brook',
    'Conception Bay South',
    'Paradise',
    'Gander',
    'Grand Falls-Windsor',
    'Happy Valley-Goose Bay',
    'Stephenville',
    'Marystown',
    'Labrador City',
    'Carbonear',
    'Bay Roberts',
    'Clarenville',
    'Bonavista',
  ],
  NS: [
    'Halifax',
    'Sydney',
    'Dartmouth',
    'Truro',
    'New Glasgow',
    'Glace Bay',
    'Kentville',
    'Amherst',
    'Bridgewater',
    'Yarmouth',
    'Antigonish',
    'Lunenburg',
    'Wolfville',
    'Baddeck',
    'Mahone Bay',
  ],
  PE: [
    'Charlottetown',
    'Summerside',
    'Cornwall',
    'Stratford',
    'Kensington',
    'Montague',
    'Alberton',
    'Souris',
    'Tignish',
    "O'Leary",
    'Georgetown',
    'Belfast',
    'St. Peters Bay',
    'Morell',
    'Hunter River',
  ],
  QC: [
    'Montreal',
    'Quebec City',
    'Laval',
    'Gatineau',
    'Longueuil',
    'Sherbrooke',
    'Saguenay',
    'Trois-Rivières',
    'Drummondville',
    'Saint-Jérôme',
    'Granby',
    'Saint-Jean-sur-Richelieu',
    'Blainville',
    'Repentigny',
    'Châteauguay',
  ],
  SK: [
    'Saskatoon',
    'Regina',
    'Prince Albert',
    'Moose Jaw',
    'Yorkton',
    'Swift Current',
    'North Battleford',
    'Estevan',
    'Lloydminster',
    'Weyburn',
    'Humboldt',
    'Melfort',
    'Rosetown',
    'Kindersley',
    'La Ronge',
  ],
  NT: [
    'Yellowknife',
    'Inuvik',
    'Hay River',
    'Fort Smith',
    'Tuktoyaktuk',
    'Norman Wells',
    'Fort Simpson',
    'Aklavik',
    'Fort Providence',
    'Behchoko',
    'Wrigley',
    'Colville Lake',
    'Gamètì',
    'Whatì',
    'Fort Liard',
  ],
  NU: [
    'Iqaluit',
    'Rankin Inlet',
    'Arviat',
    'Cambridge Bay',
    'Pangnirtung',
    'Kugluktuk',
    'Cape Dorset',
    'Igloolik',
    'Gjoa Haven',
    'Baker Lake',
    'Hall Beach',
    'Qikiqtarjuaq',
    'Kimmirut',
    'Pelly Bay',
    'Sanikiluaq',
  ],
  YT: [
    'Whitehorse',
    'Dawson City',
    'Watson Lake',
    'Haines Junction',
    'Carcross',
    'Mayo',
    'Teslin',
    'Faro',
    'Pelly Crossing',
    'Burwash Landing',
    'Beaver Creek',
    'Ross River',
    'Carmacks',
    'Old Crow',
    'Champagne',
  ],
} as Record<string, string[]>;
