name: Deploy to Netlify

on:
  push:
    branches:
      - 'author-release-*'  # Change this to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install  # or your package manager (yarn, pnpm, etc.)

      - name: Build the project
        run: cd apps/author.immigration-report.ca && yarn run prod  # or the command you use to build your project
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID__AUTHOR_SITE }}  # Add this if you want to specify the site
          NEXT_PUBLIC_GTM_ID: ${{ secrets.NEXT_PUBLIC_GTM_ID }}  # Add this if you want to specify the site


